/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package SDTL.Protocol;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class DownlinkFrame extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 731608571770129807L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"DownlinkFrame\",\"namespace\":\"SDTL.Protocol\",\"fields\":[{\"name\":\"id\",\"type\":\"int\"},{\"name\":\"TimeStampField\",\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<DownlinkFrame> ENCODER =
      new BinaryMessageEncoder<DownlinkFrame>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<DownlinkFrame> DECODER =
      new BinaryMessageDecoder<DownlinkFrame>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<DownlinkFrame> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<DownlinkFrame> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<DownlinkFrame>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this DownlinkFrame to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a DownlinkFrame from a ByteBuffer. */
  public static DownlinkFrame fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public int id;
  @Deprecated public long TimeStampField;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public DownlinkFrame() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param TimeStampField The new value for TimeStampField
   */
  public DownlinkFrame(java.lang.Integer id, java.lang.Long TimeStampField) {
    this.id = id;
    this.TimeStampField = TimeStampField;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return TimeStampField;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Integer)value$; break;
    case 1: TimeStampField = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.Integer getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.Integer value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'TimeStampField' field.
   * @return The value of the 'TimeStampField' field.
   */
  public java.lang.Long getTimeStampField() {
    return TimeStampField;
  }

  /**
   * Sets the value of the 'TimeStampField' field.
   * @param value the value to set.
   */
  public void setTimeStampField(java.lang.Long value) {
    this.TimeStampField = value;
  }

  /**
   * Creates a new DownlinkFrame RecordBuilder.
   * @return A new DownlinkFrame RecordBuilder
   */
  public static SDTL.Protocol.DownlinkFrame.Builder newBuilder() {
    return new SDTL.Protocol.DownlinkFrame.Builder();
  }

  /**
   * Creates a new DownlinkFrame RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new DownlinkFrame RecordBuilder
   */
  public static SDTL.Protocol.DownlinkFrame.Builder newBuilder(SDTL.Protocol.DownlinkFrame.Builder other) {
    return new SDTL.Protocol.DownlinkFrame.Builder(other);
  }

  /**
   * Creates a new DownlinkFrame RecordBuilder by copying an existing DownlinkFrame instance.
   * @param other The existing instance to copy.
   * @return A new DownlinkFrame RecordBuilder
   */
  public static SDTL.Protocol.DownlinkFrame.Builder newBuilder(SDTL.Protocol.DownlinkFrame other) {
    return new SDTL.Protocol.DownlinkFrame.Builder(other);
  }

  /**
   * RecordBuilder for DownlinkFrame instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<DownlinkFrame>
    implements org.apache.avro.data.RecordBuilder<DownlinkFrame> {

    private int id;
    private long TimeStampField;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(SDTL.Protocol.DownlinkFrame.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.TimeStampField)) {
        this.TimeStampField = data().deepCopy(fields()[1].schema(), other.TimeStampField);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing DownlinkFrame instance
     * @param other The existing instance to copy.
     */
    private Builder(SDTL.Protocol.DownlinkFrame other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.TimeStampField)) {
        this.TimeStampField = data().deepCopy(fields()[1].schema(), other.TimeStampField);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.Integer getId() {
      return id;
    }

    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public SDTL.Protocol.DownlinkFrame.Builder setId(int value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public SDTL.Protocol.DownlinkFrame.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'TimeStampField' field.
      * @return The value.
      */
    public java.lang.Long getTimeStampField() {
      return TimeStampField;
    }

    /**
      * Sets the value of the 'TimeStampField' field.
      * @param value The value of 'TimeStampField'.
      * @return This builder.
      */
    public SDTL.Protocol.DownlinkFrame.Builder setTimeStampField(long value) {
      validate(fields()[1], value);
      this.TimeStampField = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'TimeStampField' field has been set.
      * @return True if the 'TimeStampField' field has been set, false otherwise.
      */
    public boolean hasTimeStampField() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'TimeStampField' field.
      * @return This builder.
      */
    public SDTL.Protocol.DownlinkFrame.Builder clearTimeStampField() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public DownlinkFrame build() {
      try {
        DownlinkFrame record = new DownlinkFrame();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Integer) defaultValue(fields()[0]);
        record.TimeStampField = fieldSetFlags()[1] ? this.TimeStampField : (java.lang.Long) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<DownlinkFrame>
    WRITER$ = (org.apache.avro.io.DatumWriter<DownlinkFrame>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<DownlinkFrame>
    READER$ = (org.apache.avro.io.DatumReader<DownlinkFrame>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
